apiVersion: v1
kind: Service
metadata:
  name: ai-study-collab-service
spec:
  type: LoadBalancer
  selector:
    app: ai-study-collab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080